---
title: "Chapter 7: Bio"
styles:
  - "/chapter7/other_breaking_free_styles.css"
  - "/chapter7/bio/other_bio_styles.css"
  - "/chapter7/bio/bio.css"
---

<section class="bio">
  <figure>
    <img width="90px" height="90px" src="/chapter7/bio/profile.svg">
  </figure>
  <p>
    Landon is a developer and entrepreneur based in Seattle. He's the author of the Flexbox Starter Course and Unraveling Flexbox, a book on how to create modern, responsive layouts in CSS.
  </p>
</section>
